crawling:
  crawl: true
  delay: 1
  exclude_patterns:
  - /api/
  - /search
  - \.xml$
  - /login
  - /logout
  headers:
    User-Agent: Mozilla/5.0 (compatible; DocCrawler/1.0; +https://example.com/bot)
  include_patterns: []
  max_pages: -1
  num_threads: 20
  skip_extensions:
  - .pdf
  - .jpg
  - .png
  - .gif
  - .css
  - .js
  - .svg
  - .ico
  - .json
  - .xml
  - .yaml
  timeout: 10
output:
  dest_github_repo: git@github.com:dyingc/mcp_docs.git
  directory: docs_output/mcp
  frontmatter:
    crawled_date: '2025-06-09'
    source: mcp-docs
  ignore_images: false
  ignore_links: false
  llms_doc_prefix: mcp
  llms_txt:
    description: Complete MCP documentation for AI assistance
    include_urls: true
    title: MCP Documentation
  minimal_size: 1
  output_llms_txt: false
site:
  allowed_domains:
  - docs.anthropic.com
  content_selectors:
  - main
  - article
  - .content
  - .documentation
  link_selectors:
  - a[href]
  name: n8n Documentation
  remove_selectors:
  - nav
  - header
  - footer
  - .navbar
  - .nav
  - .sidebar
  - .menu
  - .breadcrumb
  - .pagination
  - script
  - style
  - noscript
  - .search-box
  start_urls: []
  title_selectors:
  - title
  - h1
  - .page-title
  url: https://docs.anthropic.com/en/docs/agents-and-tools/mcp
