crawling:
  crawl: false
  delay: 1
  exclude_patterns:
  - /api/
  - /search
  - \.xml$
  - /login
  - /logout
  headers:
    User-Agent: Mozilla/5.0 (compatible; DocCrawler/1.0; +https://example.com/bot)
  include_patterns: []
  max_depth: 2
  max_pages: -1
  num_threads: 20
  skip_extensions:
  - .pdf
  - .jpg
  - .png
  - .gif
  - .css
  - .js
  - .svg
  - .ico
  - .json
  - .xml
  - .yaml
  timeout: 10
  file_extensions:
  - .md
  - .rst
  - .txt
  - .py
  - .js
  - .ts
  - .html
  - .css
  - .json
  - .yaml
  - .yml
link_processing:
  url_prefix: 'https://github.com/modelcontextprotocol/python-sdk/blob/main'
output:
  dest_github_repo: git@github.com:dyingc/mcp_docs.git
  directory: docs_output/mcp-python-sdk
  frontmatter:
    crawled_date: '2025-06-13'
  ignore_images: false
  ignore_links: false
  llm_concurrency: 1
  llms_doc_prefix: mcp-python-sdk
  llms_txt:
    description: Complete MCP Python SDK documentation for AI assistance
    include_urls: true
    title: MCP Python SDK Documentation
  minimal_size: 128
  output_llms_txt: true
site:
  allowed_domains:
  - github.com
  - raw.githubusercontent.com
  content_selectors:
  - main
  - article
  - .content
  - .documentation
  link_selectors:
  - a[href]
  name: MCP Documentation
  remove_selectors:
  - nav
  - header
  - footer
  - .navbar
  - .nav
  - .sidebar
  - .menu
  - .breadcrumb
  - .pagination
  - script
  - style
  - noscript
  - .search-box
  start_urls: []
  title_selectors:
  - title
  - h1
  - .page-title
  url: https://github.com/modelcontextprotocol/python-sdk
