crawling:
  delay: 1.0
  exclude_patterns:
  - /api/
  - /search
  - \.xml$
  - /login
  - /logout
  headers:
    User-Agent: Mozilla/5.0 (compatible; DocCrawler/1.0; +https://example.com/bot)
  include_patterns: []
  max_pages: 100
  skip_extensions:
  - .pdf
  - .jpg
  - .png
  - .gif
  - .css
  - .js
  - .svg
  - .ico
  timeout: 10
output:
  directory: docs_output
  frontmatter:
    crawled_date: '2024-01-01'
    source: n8n-docs
  ignore_images: false
  ignore_links: false
  llms_txt:
    description: Complete n8n documentation for AI assistance
    include_urls: true
    title: n8n Documentation
site:
  allowed_domains:
  - docs.n8n.io
  content_selectors:
  - main
  - article
  - .content
  - .documentation
  link_selectors:
  - a[href]
  name: n8n Documentation
  remove_selectors:
  - nav
  - header
  - footer
  - .navbar
  - .nav
  - .sidebar
  - .menu
  - .breadcrumb
  - .pagination
  - script
  - style
  - noscript
  - .search-box
  start_urls: []
  title_selectors:
  - title
  - h1
  - .page-title
  url: https://docs.n8n.io/
